### ISSUE TITLE
Error in browser.umd.js

### ISSUE THREAD

**Issue by chirag0110** [VirgilSecurity/demo-e3kit-web#3]
Hello @cardoso @MariiaMalitska @dkosolap 

When trying to run this web demo. It gives the below error in the browser.umd.js file.

It was working fine before but suddenly stop working. please fix this.

Getting This Error- **Uncaught ReferenceError: require is not defined**

**Comment by chirag0110** [comment]
Hello Team,

Any update on this issue?

**Comment by rstp-god** [comment]
@chirag0110 Hello! Sorry for being late, fix this in new release 2.5.2 try it now!

**Comment by chirag0110** [comment]
Hekllo @azirb Thank You for your response.

Yes that error has been resolved but after updating  browser.umd.js (2.5.2) with newer version it gives new error.

**Uncaught TypeError: Cannot set properties of undefined (setting 'Stream')**

Please can you fix this.

Thank in advance :)

**Comment by rstp-god** [comment]
Hello @chirag0110 ! Fixed your problem in new 2.5.4 release! Thanks for reporting!

**Comment by rstp-god** [comment]
Closing the ticket as fixed. Please create a new one if there are any more issues
